name: meal_recommendations
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Firebase
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  # A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  flutter_screenutil: ^5.9.3
  # Provides A collection of animated loading indicators
  loading_indicator: ^3.1.1
  # For internet connectivity checking
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.0
  # For state management
  flutter_bloc: ^8.1.6
  # Code generator (mainly used with Bloc)
  freezed_annotation: ^2.4.4
  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.13
  # Code generator (mainly used with Bloc)
  freezed: ^2.5.7
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/svgs/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_28pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter_28pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter_28pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter_28pt-Bold.ttf
          weight: 700


flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null